# generated by datamodel-codegen:
#   filename:  osmosis_pools.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class PoolParams(BaseModel):
    exit_fee: str
    swap_fee: str
    smooth_weight_change_params: None


class TotalShares(BaseModel):
    denom: str
    amount: str


class PoolLiquidityItem(BaseModel):
    denom: str
    amount: str


class Token(BaseModel):
    denom: str
    amount: str


class PoolAsset(BaseModel):
    token: Token
    weight: str


class ModelItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    id: Optional[str] = None
    pool_params: Optional[PoolParams] = None
    total_shares: Optional[TotalShares] = None
    liquidityUsd: float
    liquidity24hUsdChange: float
    volume24hUsd: float
    volume24hUsdChange: float
    volume7dUsd: float
    taker_fee: str
    pool_liquidity: Optional[List[PoolLiquidityItem]] = None
    scaling_factors: Optional[List[str]] = None
    scaling_factor_controller: Optional[str] = None
    pool_assets: Optional[List[PoolAsset]] = None
    total_weight: Optional[str] = None
    address: Optional[str] = None
    current_tick_liquidity: Optional[str] = None
    token0: Optional[str] = None
    token0Amount: Optional[str] = None
    token1: Optional[str] = None
    token1Amount: Optional[str] = None
    current_sqrt_price: Optional[str] = None
    current_tick: Optional[str] = None
    tick_spacing: Optional[str] = None
    exponent_at_price_one: Optional[str] = None
    spread_factor: Optional[str] = None
    contract_address: Optional[str] = None
    pool_id: Optional[str] = None
    code_id: Optional[str] = None
    instantiate_msg: Optional[str] = None
    tokens: Optional[List[Token]] = None


class Model(RootModel[List[ModelItem]]):
    root: List[ModelItem]
